parameters:
    redis.config.connection:
        scheme: 'tcp'
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        password: '%env(DB_PASSWORD)%'
        username: '%env(DB_USER)%'
    redis.config.options:
        prefix: 'inventory:'
        database: 0

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Application\:
        resource: '../src/Application'

    Domain\:
        resource: '../src/Domain'
        exclude:
            - '../src/Domain/Model'

    Infrastructure\:
        resource: '../src/Infrastructure'
        exclude:
            - '../src/Infrastructure/Framework/Symfony/Kernel.php'
            - '../src/Infrastructure/Persistence/Redis/Entity'

    Presentation\:
        resource: '../src/Presentation'

    Presentation\Console\RestoreInventory\SetInventoryCommand:
        autoconfigure: false
        tags:
            - { name: 'console.command', command: 'coin-inventory:restore', description: 'Clears coin inventory and sets prepared collection' }

    Predis\Client: ['%redis.config.connection%', '%redis.config.options%']
    Predis\ClientInterface: '@Predis\Client'

    Domain\Market\Repository\MarketRepositoryInterface:
        alias: Infrastructure\XAUS\Guzzle\XausRepository

    Infrastructure\XAUS\Guzzle\XausRepository:
        arguments: ["@guzzle.xaus.client"]

    guzzle.xaus.client:
        class: GuzzleHttp\Client
        arguments:
            $config:
                base_uri: 'https://xaus.com/api/v1/'
                timeout: 10
                handler: '@guzzle.handler'

    guzzle.handler:
        class: GuzzleHttp\HandlerStack
        factory: ['GuzzleHttp\HandlerStack', 'create']
        calls:
            - method: push
              arguments: ['@Kevinrob\GuzzleCache\CacheMiddleware']

    Kevinrob\GuzzleCache\CacheMiddleware:
        arguments: ['@Kevinrob\GuzzleCache\Strategy\GreedyCacheStrategy']

    Kevinrob\GuzzleCache\Strategy\GreedyCacheStrategy:
        arguments:
            $cache: '@Kevinrob\GuzzleCache\Storage\FlysystemStorage'
            $defaultTtl: 3600

    Kevinrob\GuzzleCache\Storage\FlysystemStorage:
        arguments: ['@League\Flysystem\Local\LocalFilesystemAdapter']

    League\Flysystem\Local\LocalFilesystemAdapter:
        arguments:
            $location: '/app/var/cache/%kernel.environment%'
